name: Build
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          pacman -Syu --noconfirm --needed wget
          wget https://github.com/seeseemelk/xtensa-esp32-elf-binutils-pkgbuild/releases/download/v2.35-1/xtensa-esp32-elf-binutils-2.35-1-x86_64.pkg.tar.zst
		  wget https://github.com/seeseemelk/xtensa-esp32-elf-gcc-bootstrap-pkgbuild/releases/download/v12.0.0-1/xtensa-esp32-elf-gcc-bootstrap-12.0.0-1-x86_64.pkg.tar.zst
          pacman -U --noconfirm *.pkg.*
          rm *.pkg.*
          useradd -m build
          chown -R build .
      - name: Make package
        run: su build -c "makepkg -s --skippgpcheck"
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pkg.*"
